//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using NoidaAuthority.PMS.Entities;
namespace NoidaAuthority.PMS.Repository.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NOIDANEWEntities : DbContext
    {
        public NOIDANEWEntities()
            : base("name=NOIDANEWEntities")
        {
        }
    
        
    
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Role_Menu_Mapping> Role_Menu_Mapping { get; set; }
        public virtual DbSet<Role_Users> Role_Users { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<NAcustomer> NAcustomers { get; set; }
        public virtual DbSet<view_property> view_property { get; set; }
        public virtual DbSet<Customer_Feedback> Customer_Feedback { get; set; }
        public virtual DbSet<CitizenService_Master> CitizenService_Master { get; set; }
        public virtual DbSet<Customer_ServiceRequest> Customer_ServiceRequest { get; set; }
        public virtual DbSet<LookupDepartment> LookupDepartments { get; set; }
        public virtual DbSet<Property_Remarks> Property_Remarks { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<sp_GetPropertyPaymentHistoryByRegistrationId_Result> sp_GetPropertyPaymentHistoryByRegistrationId(Nullable<int> registrationId)
        {
            var registrationIdParameter = registrationId.HasValue ?
                new ObjectParameter("RegistrationId", registrationId) :
                new ObjectParameter("RegistrationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetPropertyPaymentHistoryByRegistrationId_Result>("sp_GetPropertyPaymentHistoryByRegistrationId", registrationIdParameter);
        }
    }
}
