//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoidaAuthority.PMS.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountData
    {
        public string PRDVREGISTRATION_ID { get; set; }
        public string PLDIPROPERTY_NO { get; set; }
        public string LocationCharge { get; set; }
        public Nullable<decimal> landRatePerSqmt { get; set; }
        public Nullable<decimal> totalArea { get; set; }
        public Nullable<decimal> totalPropertyCost { get; set; }
        public string ApplicantName { get; set; }
        public string allotmentDate { get; set; }
        public string LeaseDeedDate { get; set; }
        public Nullable<decimal> C1 { get; set; }
        public Nullable<decimal> C3 { get; set; }
        public Nullable<decimal> C4 { get; set; }
        public Nullable<decimal> C6 { get; set; }
        public Nullable<decimal> C7 { get; set; }
        public Nullable<decimal> C8 { get; set; }
        public Nullable<decimal> C9 { get; set; }
        public Nullable<decimal> C22 { get; set; }
        public Nullable<decimal> C24 { get; set; }
        public Nullable<decimal> C30 { get; set; }
        public Nullable<decimal> C31 { get; set; }
        public Nullable<decimal> C51 { get; set; }
        public Nullable<decimal> C97 { get; set; }
        public Nullable<decimal> C98 { get; set; }
        public Nullable<decimal> C99 { get; set; }
    }
}
