//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoidaAuthority.PMS.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankMst
    {
        public BankMst()
        {
            this.ApplicationPaymentDetails = new HashSet<ApplicationPaymentDetail>();
            this.BranchMsts = new HashSet<BranchMst>();
            this.SchemeBankTrans = new HashSet<SchemeBankTran>();
        }
    
        public int bankId { get; set; }
        public string bankName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
    
        public virtual ICollection<ApplicationPaymentDetail> ApplicationPaymentDetails { get; set; }
        public virtual ICollection<BranchMst> BranchMsts { get; set; }
        public virtual ICollection<SchemeBankTran> SchemeBankTrans { get; set; }
    }
}
