//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoidaAuthority.PMS.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Letter_History
    {
        public int Id { get; set; }
        public Nullable<int> Department_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> Rid { get; set; }
        public string Template_Html { get; set; }
        public Nullable<System.DateTime> Generate_Date { get; set; }
        public Nullable<bool> Is_Verified { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> Template_Id { get; set; }
        public string Barcode_Val { get; set; }
        public Nullable<bool> Is_Dispatched { get; set; }
        public Nullable<System.DateTime> Dispatch_Date { get; set; }
        public Nullable<int> ServiceRequestId { get; set; }
        public string Comment { get; set; }
    
        public virtual DepartmentMst DepartmentMst { get; set; }
    }
}
