//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoidaAuthority.PMS.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class LitigationMst
    {
        public int Id { get; set; }
        public Nullable<int> RId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string CaseNo { get; set; }
        public Nullable<System.DateTime> CaseFiledDate { get; set; }
        public string Court { get; set; }
        public string Parties { get; set; }
        public string Description { get; set; }
        public string Advocate { get; set; }
        public string AdvocateDetails { get; set; }
        public string StayOrder { get; set; }
        public string CaseFiledStatus { get; set; }
        public Nullable<System.DateTime> LegalDate { get; set; }
        public string NarrativeEyes { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
