//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoidaAuthority.PMS.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEIPT_AMOUNT_TRAN
    {
        public Nullable<decimal> RECEIPT_ID { get; set; }
        public Nullable<decimal> DEPT_CODE { get; set; }
        public Nullable<decimal> RECEIPT_HEAD_ID { get; set; }
        public Nullable<decimal> RECEIPT_SUBHEAD_ID { get; set; }
        public string CHALLAN_ID { get; set; }
        public System.DateTime DEPOSIT_DATE { get; set; }
        public decimal AMOUNT_PAID { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public string USERID { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
    }
}
