//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoidaAuthority.PMS.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusMaster
    {
        public StatusMaster()
        {
            this.OnlineExtensionDetails = new HashSet<OnlineExtensionDetail>();
            this.OnlineFunctionalDetails = new HashSet<OnlineFunctionalDetail>();
            this.OnlineMortgageDetails = new HashSet<OnlineMortgageDetail>();
            this.OnlineRentPermissionDetails = new HashSet<OnlineRentPermissionDetail>();
            this.OnlineTransferMutations = new HashSet<OnlineTransferMutation>();
            this.Extension_Details = new HashSet<Extension_Details>();
            this.FunctionalDetails = new HashSet<FunctionalDetail>();
            this.MortgageDetails = new HashSet<MortgageDetail>();
            this.PossessionDetails = new HashSet<PossessionDetail>();
            this.RentPermissionDetails = new HashSet<RentPermissionDetail>();
            this.Succ_Mut_Trans = new HashSet<Succ_Mut_Trans>();
        }
    
        public int Id { get; set; }
        public string Status { get; set; }
        public string StatusType { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Modifiedby { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<OnlineExtensionDetail> OnlineExtensionDetails { get; set; }
        public virtual ICollection<OnlineFunctionalDetail> OnlineFunctionalDetails { get; set; }
        public virtual ICollection<OnlineMortgageDetail> OnlineMortgageDetails { get; set; }
        public virtual ICollection<OnlineRentPermissionDetail> OnlineRentPermissionDetails { get; set; }
        public virtual ICollection<OnlineTransferMutation> OnlineTransferMutations { get; set; }
        public virtual ICollection<Extension_Details> Extension_Details { get; set; }
        public virtual ICollection<FunctionalDetail> FunctionalDetails { get; set; }
        public virtual ICollection<MortgageDetail> MortgageDetails { get; set; }
        public virtual ICollection<PossessionDetail> PossessionDetails { get; set; }
        public virtual ICollection<RentPermissionDetail> RentPermissionDetails { get; set; }
        public virtual ICollection<Succ_Mut_Trans> Succ_Mut_Trans { get; set; }
    }
}
