//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NoidaAuthority.PMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.Role_Menu_Mapping = new HashSet<Role_Menu_Mapping>();
            this.Role_Users = new HashSet<Role_Users>();
        }
    
        public int RoleId { get; set; }
        public string RoleName { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual ICollection<Role_Menu_Mapping> Role_Menu_Mapping { get; set; }
        public virtual ICollection<Role_Users> Role_Users { get; set; }
    }
}
