//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoidaAuthority.PMS.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NAResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NAResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NoidaAuthority.PMS.Common.Resources.NAResources", typeof(NAResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User,&lt;br&gt;&lt;br&gt;Your account has been deactivated. &lt;br&gt; Regards, http://mynoida.in.
        /// </summary>
        public static string Email_AccountDeActivated {
            get {
                return ResourceManager.GetString("Email_AccountDeActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User,&lt;br&gt;&lt;br&gt;You have successfully changed your password. Your new password is {0}. DO NOT disclose this to anyone by any means.&lt;br&gt;Regards, http://mynoida.in.
        /// </summary>
        public static string Email_ChangePassword {
            get {
                return ResourceManager.GetString("Email_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi,&lt;br&gt;&lt;br&gt;A new User has registered with resgistration no. {0} . Please check and reply..
        /// </summary>
        public static string Email_Registration {
            get {
                return ResourceManager.GetString("Email_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Processing fee for {0} against request id {1} of amount {2} has been paid successfully, Noida Authority.
        /// </summary>
        public static string OnlineProcessingFee {
            get {
                return ResourceManager.GetString("OnlineProcessingFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Your online service request has been submitted successfully with request no is {0}. Regards, http:http://mynoida.in.
        /// </summary>
        public static string OnlineServiceRequest {
            get {
                return ResourceManager.GetString("OnlineServiceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Your account has been deactivated. Regards, http://mynoida.in.
        /// </summary>
        internal static string SMS_AccountDeActivated {
            get {
                return ResourceManager.GetString("SMS_AccountDeActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, You are successfully registered with mynoida.in. Your user name is{0}and password is{1}Regards, http://mynoida.in.
        /// </summary>
        public static string SMS_ActivateRegistration {
            get {
                return ResourceManager.GetString("SMS_ActivateRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, You have successfully changed your password. Your new password is {0}. Regards, http://mynoida.in.
        /// </summary>
        public static string SMS_ChangePassword {
            get {
                return ResourceManager.GetString("SMS_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Your OTP is {0}. DO NOT disclose this OTP to anyone. This is for online use by you only. Regards, http://mynoida.in.
        /// </summary>
        public static string SMS_OTPMessage {
            get {
                return ResourceManager.GetString("SMS_OTPMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Registration Process has been completed successfully..
        /// </summary>
        public static string SMS_Registration {
            get {
                return ResourceManager.GetString("SMS_Registration", resourceCulture);
            }
        }
    }
}
